package com.model;

/**
 * THuifu generated by MyEclipse Persistence Tools
 */

public class THuifu implements java.io.Serializable
{

	private Integer id;
	private String title;
	private String content;
	private String shijian;

	private Integer stuId;
	private Integer zhutiId;
	
	private TStu stu;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getShijian() {
		return shijian;
	}

	public void setShijian(String shijian) {
		this.shijian = shijian;
	}


	public Integer getZhutiId() {
		return zhutiId;
	}

	public void setZhutiId(Integer zhutiId) {
		this.zhutiId = zhutiId;
	}

	public Integer getStuId() {
		return stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public TStu getStu() {
		return stu;
	}

	public void setStu(TStu stu) {
		this.stu = stu;
	}

	
}